const fs = require('fs');
const path = require('path');

const routesDir = path.join(__dirname, 'routes', 'v1');
const outputFile = path.join(__dirname, 'Digital-Evaluation-Postman.json');

const collection = {
    info: {
        name: 'Digital Evaluation Platform V1 (Zero Config)',
        description: 'Autogenerated Postman Collection including real schema payload data. No environment necessary.',
        schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json'
    },
    item: [],
    auth: {
        type: 'bearer',
        bearer: [ { key: 'token', value: '{{adminToken}}', type: 'string' } ]
    },
    event: [ { listen: 'prerequest', script: { type: 'text/javascript', exec: [''] } } ],
    variable: [ 
        { key: 'baseUrl', value: 'http://localhost:3000/api/v1', type: 'string' },
        { key: 'adminToken', value: '', type: 'string' }
    ]
};

function formatFolderName(filename) {
    const base = filename.replace('.js', '');
    if (base === 'index') return null;
    return base.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
}

function getRealisticBody(folderName, endpointPath) {
    if (folderName === 'Auth') {
        if (endpointPath === '/login') {
            return '{\n    "identifier": "alice.johnson@example.com",\n    "password": "1234"\n}';
        }
        if (endpointPath === '/logout' || endpointPath === '/verify-token') {
            return '{}';
        }
    } else if (folderName === 'Users') {
        if (endpointPath.includes('/roles')) return '{\n    "role_id": 2\n}';
        if (endpointPath.includes('/change-password')) return '{\n    "currentPassword": "1234",\n    "newPassword": "new_password_1234"\n}';
        return '{\n    "name": "Jane Doe",\n    "email": "jane.doe@test.com",\n    "password": "securepassword123",\n    "role_id": 3\n}';
    } else if (folderName === 'Classes') {
        return '{\n    "grade": 10,\n    "section": "A",\n    "academic_year": 2024\n}';
    } else if (folderName === 'Subjects') {
        return '{\n    "name": "Mathematics",\n    "code": "MATH101",\n    "description": "Basic Math"\n}';
    } else if (folderName === 'Students') {
        return '{\n    "name": "Student One",\n    "email": "studentnew@test.com",\n    "password": "password123",\n    "institution_id": "STU100",\n    "class_id": 1\n}';
    } else if (folderName === 'Faculty') {
        return '{\n    "name": "Faculty Name",\n    "email": "facultynew@test.com",\n    "password": "password123",\n    "department": "Science"\n}';
    } else if (folderName === 'Exam Schedules') {
        return '{\n    "class_id": 1,\n    "subject_id": 1,\n    "exam_datetime": "2024-05-20T10:00:00Z",\n    "title": "Midterm Exam"\n}';
    } else if (folderName === 'Assignments') {
        return '{\n    "faculty_id": 1,\n    "subject_id": 1,\n    "class_id": 1\n}';
    } else if (folderName === 'Submissions') {
        return '{\n    "student_id": 1,\n    "exam_schedule_id": 1,\n    "submission_type_id": 1,\n    "status_id": 1,\n    "submitted_at": "2024-05-20T12:00:00Z"\n}';
    } else if (folderName === 'Documents') {
        return '{\n    "submission_id": 1,\n    "title": "Answer Sheet PDF"\n}';
    } else if (folderName === 'Files') {
        if (endpointPath.includes('/versions')) {
            return '{\n    "blob_name": "scan_v2.pdf",\n    "container_name": "submissions",\n    "etag": "xyz789"\n}';
        }
        return '{\n    "document_id": 1,\n    "original_file_name": "scan.pdf",\n    "mime_type": "application/pdf",\n    "file_size_kb": 1024,\n    "file_type_id": 1,\n    "blob_name": "scan_v1.pdf",\n    "container_name": "submissions"\n}';
    } else if (folderName === 'Pages') {
        return '{\n    "file_id": 1,\n    "version_id": 1,\n    "pages": [\n        {"page_number": 1, "blob_name": "p1.jpg", "container_name": "pages"},\n        {"page_number": 2, "blob_name": "p2.jpg", "container_name": "pages"}\n    ]\n}';
    } else if (folderName === 'Evaluations') {
        return '{\n    "submission_id": 1,\n    "marks_awarded": 85,\n    "max_marks": 100,\n    "remarks": "Good Work",\n    "status_id": 2\n}';
    } else if (folderName === 'Annotations') {
        return '{\n    "evaluation_id": 1,\n    "page_id": 1,\n    "annotation_type_id": 1,\n    "pos_x": 10.5,\n    "pos_y": 20.0,\n    "pos_width": 100,\n    "pos_height": 50,\n    "content": "Check here"\n}';
    } else if (folderName === 'Roles') {
        return '{\n    "name": "Moderator"\n}';
    } else if (folderName === 'Permissions') {
        return '{\n    "name": "edit_grades",\n    "description": "Can edit grades"\n}';
    } else if (folderName === 'Notifications') {
        return '{\n    "user_id": 1,\n    "entity_type": "submissions",\n    "entity_id": 1,\n    "message": "System Alert"\n}';
    } else if (folderName === 'Audit Logs') {
        return '{\n    "entity_type": "users",\n    "entity_id": 1,\n    "field_name": "status",\n    "old_value": "active",\n    "new_value": "inactive"\n}';
    }
    return '{\n    "example_field": "value"\n}';
}

const files = fs.readdirSync(routesDir);

files.forEach(file => {
    if (!file.endsWith('.js') || file === 'index.js') return;

    const folderName = formatFolderName(file);
    const content = fs.readFileSync(path.join(routesDir, file), 'utf8');

    const folder = { name: folderName, item: [] };
    let currentRoutePath = '';
    const lines = content.split('\n');

    for (let line of lines) {
        const standaloneMatch = /router\.(get|post|put|patch|delete)\(\s*['"`](.*?)['"`]/.exec(line);
        if (standaloneMatch) {
            pushEndpoint(standaloneMatch[1].toUpperCase(), standaloneMatch[2]);
            continue;
        }

        const routeMatch = /router\.route\(\s*['"`](.*?)['"`]\)/.exec(line);
        if (routeMatch) {
            currentRoutePath = routeMatch[1];
            const sameLineMatches = [...line.matchAll(/\.(get|post|put|patch|delete)\(/g)];
            if (sameLineMatches.length > 0) {
                for (let m of sameLineMatches) {
                    pushEndpoint(m[1].toUpperCase(), currentRoutePath);
                }
            }
            continue;
        }

        if (currentRoutePath !== '') {
            const chainMatch = /^\s*\.(get|post|put|patch|delete)\(/.exec(line);
            if (chainMatch) {
                pushEndpoint(chainMatch[1].toUpperCase(), currentRoutePath);
            }
        }
    }

    function pushEndpoint(method, endpointPath) {
        let reqName = `${method} ${endpointPath === '/' ? '' : endpointPath}`;
        
        const pathVariables = [];
        const postmanUrlPath = endpointPath.split('/').filter(p => p !== '').map(segment => {
            if (segment.startsWith(':')) {
                const varName = segment.substring(1);
                let defaultValue = '1';
                if (varName === 'user_id') defaultValue = '{{currentUserId}}';
                pathVariables.push({ key: varName, value: defaultValue });
                return `:${varName}`;
            }
            return segment;
        });

        const requestItem = {
            name: reqName,
            request: {
                method: method,
                header: [ { key: 'Content-Type', value: 'application/json' } ],
                url: {
                    raw: `{{baseUrl}}/${file.replace('.js', '')}${endpointPath === '/' ? '' : endpointPath}`,
                    host: ['{{baseUrl}}'],
                    path: [file.replace('.js', ''), ...postmanUrlPath]
                }
            },
            response: []
        };

        if (pathVariables.length > 0) {
            requestItem.request.url.variable = pathVariables;
        }

        if (method === 'GET' && !endpointPath.includes(':')) {
            requestItem.request.url.query = [
                { key: 'page', value: '1' },
                { key: 'limit', value: '10' },
                { key: 'sort', value: 'desc' }
            ];
            requestItem.request.url.raw += '?page=1&limit=10&sort=desc';
        }

        if (['POST', 'PUT', 'PATCH'].includes(method)) {
            const realBody = getRealisticBody(folderName, endpointPath);
            requestItem.request.body = {
                mode: 'raw',
                raw: realBody,
                options: { raw: { language: 'json' } }
            };
            
            // KEY FIX: Use pm.collectionVariables.set instead of pm.environment.set
            if (folderName === 'Auth' && endpointPath === '/login' && method === 'POST') {
                requestItem.event = [{
                    listen: 'test',
                    script: {
                        exec: [
                            'var response = pm.response.json();',
                            'if (response.success !== false && response.data) {',
                            '    if (response.data.token) pm.collectionVariables.set("adminToken", response.data.token);',
                            '    if (response.data.user && response.data.user.user_id) pm.collectionVariables.set("currentUserId", response.data.user.user_id.toString());',
                            '}'
                        ],
                        type: 'text/javascript'
                    }
                }];
            }
        }
        folder.item.push(requestItem);
    }

    if (folder.item.length > 0) folder.item.sort((a,b) => a.name.localeCompare(b.name));
    if (folder.item.length > 0) collection.item.push(folder);
});

fs.writeFileSync(outputFile, JSON.stringify(collection, null, 4));
console.log(`Successfully generated Postman Collection with real schema at: ${outputFile}`);
